# Generated by Django 4.2 on 2023-11-18 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AoEscolar',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('año_escolar', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('materia', models.CharField(max_length=100)),
                ('c_año_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.aoescolar')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('dni', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('apellidos', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('edad', models.CharField(blank=True, max_length=2, null=True)),
                ('telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('fecha_de_nac', models.CharField(blank=True, max_length=10, null=True)),
                ('año_cursante', models.CharField(blank=True, max_length=100)),
                ('promedio', models.CharField(blank=True, max_length=5)),
                ('observacion', models.TextField(blank=True)),
                ('userr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TercerLapso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('definitiva', models.CharField(blank=True, max_length=2)),
                ('codigo_asig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.asignaturas')),
                ('codigo_año', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.aoescolar')),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.estudiante')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SegundoLapso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('definitiva', models.CharField(blank=True, max_length=2)),
                ('codigo_asig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.asignaturas')),
                ('codigo_año', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.aoescolar')),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.estudiante')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrimerLapso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('definitiva', models.CharField(blank=True, max_length=2)),
                ('codigo_asig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.asignaturas')),
                ('codigo_año', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.aoescolar')),
                ('dni', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_web.estudiante')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materias_año',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.CharField(max_length=100)),
                ('materia', models.CharField(max_length=100)),
                ('codigo_asig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.asignaturas')),
                ('codigo_año', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.aoescolar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EAoEsc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_año_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.aoescolar')),
                ('userr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='docent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido_materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivos', models.FileField(null=True, upload_to='')),
                ('id_materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_web.materias_año')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
